#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry "Windows 8" {
	insmod ntfs
	insmod fat
	set root='hd1,gpt1'
	search --no-floppy --fs-uuid --set=root A237-3DDD
	chainloader /EFI/Boot/bootx64.efi
}
